### ISSUE TITLE
我感觉这就是个烂尾工程啊

### ISSUE THREAD

**Issue by vihor3** [izhaoo/wordpress-theme-pure#2]
哎，水平不够，坑填不上，主题还是很喜欢的，等能填坑再用吧

**Comment by zhaoo** [comment]
确实废弃了……无颜面对江东父老……
厚着脸皮推广一下：[hexo-theme-zhaoo](https://github.com/izhaoo/hexo-theme-zhaoo)

**Comment by zhaoo** [comment]
Sorry...
